<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../cebe/markdown/bin/markdown)
 * using a stream wrapper to prevent the shebang from being output on PHP<8
 *
 * @generated
 */

namespace app\controllers;

use Yii;
use FrontEndCotroller;
use app\models\Forum;
use app\models\Country;
use app\models\Region;
use app\models\City;
use app\models\CommentPhone;
use yii\data\Pagination;

/**
 * Implements hook_help().
 */
class CityController extends FrontEndController
{

    public function actionIndex($link, $cityId = 0)
    {
        $city = City::find()->where(['id' => $cityId])->one();
        if ($city == null) {
            throw new \yii\web\NotFoundHttpException('Oopsss1');
        }
        $region = $city->region;
        $country = $city->country;

        $forums = Forum::find()
            ->joinWith('user')
            ->joinWith('country')
            ->joinWith('region')
            ->joinWith('city')
            ->where(
                [
                    'forum.city_id' => [$city->id, 0],
                    'forum.region_id' => [$city->region_id, 0],
                    'forum.country_id' => [$city->country_id],
                    'forum.status' => [Forum::STATUS_APPROVED, Forum::STATUS_NEW]
                ]
            )
            ->orderBy('datetime_create DESC')
            ->limit(5)
            ->all();

        $comments = CommentPhone::find()
            ->joinWith('phoneInfo')
            ->where('comment_phone.status=:status AND phone_info.city_id=:city_id', ['status' => CommentPhone::STATUS_OK, 'city_id' => $city->id])
            //->orderBy('datetime DESC')
            ->limit(5)
            ->all();


        $this->metaUrl = '[city_url]';
        $this->canonical = $city->getLink();

        $this->metaReplace = [
            '[city]' => $city->name,
            '[city_v]' => $city->name_v,
            '[city_net]' => $city->name_net,
            '[city_vin]' => $city->name_vin,
            '[city_url]' => $city->link,
            '[region]' => $region != null ? $region->name : '',
            '[region_v]' => $region != null ? $region->name_v : '',
            '[region_net]' => $region != null ? $region->name_net : '',
            '[region_url]' => $region != null ? $region->link : '',
            '[date]' => \app\lib\CommonLib::dateRu('F Y'),
            '[country]' => $country != null ? $country->name : '',
            '[country_v]' => $country != null ? $country->name_v : '',
            '[country_net]' => $country != null ? $country->name_net : '',
            '[country_vin]' => $country != null ? $country->name_vin : '',
            '[country_url]' => $country != null ? $country->link : '',
            '[v_vo_na]' => $country != null ? $country->v_vo_na : '',
            '[V_VO_NA]' =>  $country != null ? \app\lib\CommonLib::mb_ucfirst($country->v_vo_na) : ''
        ];


        return $this->render('city', ['forums' => $forums, 'commentPhones' => $comments, 'city' => $city]);
    }
}
