<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../cebe/markdown/bin/markdown)
 * using a stream wrapper to prevent the shebang from being output on PHP<8
 *
 * @generated
 */

namespace app\controllers;

use Yii;
use FrontEndCotroller;
use app\models\Forum;

/**
 * Implements hook_help().
 */
class ForumController extends FrontEndController
{

    public function actionShow($forum_id)
    {

        $forum = Forum::find()->where(['id' => $forum_id])->with('tags')->one();
        if ($forum === null)
            throw new \yii\web\NotFoundHttpException('Oopsss!');
        if (!$forum->isAvailable())
            throw new \yii\web\NotFoundHttpException('Oopsss!!');

        // if ($forum->city != null) $this->cityV = $forum->city;
        // else if ($forum->region != null) $this->regionV = $forum->region;
        // else if ($forum->country != null) $this->countryV = $forum->country;

        // $criteria = new CDbCriteria;
        // $criteria->condition = 'forum_id=:forum_id AND 
        //     (
        //         (status IN (' . ForumComment::STATUS_NEW . ',' . ForumComment::STATUS_APPROVED . ')) OR 
        //         (status=' . ForumComment::STATUS_DELETED . ' AND ip=INET_ATON(:ip) AND datetime_create>UNIX_TIMESTAMP()-3600) 
        //     )';
        // $criteria->params = array('forum_id' => $forum_id, 'ip' => $_SERVER['REMOTE_ADDR']);
        // $criteria->order = 'datetime_create ASC';
        // $comments = ForumComment::model()->with(array('user'))->findAll($criteria);

        // $tmp = array();
        // foreach ($comments as $row) {
        //     $tmp[$row->id] = $row;
        // }
        // $comments = $tmp;
        // unset($tmp);

        // $videos = ForumVideo::getVideoForum($forum_id);
        // $pics = ForumPhoto::getVideoForum($forum_id);
        $this->canonical = $forum->getLink();

        $this->h1 = $forum->title;
        if (!empty($forum->meta_title)) $this->pageTitle = $forum->meta_title;
        else $this->pageTitle = $forum->title;
        if (!empty($forum->meta_keyword)) $this->pageKeywords = $forum->meta_keyword;
        else $this->pageKeywords = $forum->title;
        if (!empty($forum->meta_description)) $this->pageDescription = $forum->meta_description;
        else {
            $this->pageDescription = trim(str_replace(array("\r", "\n"), ' ', $forum->getSubText()));
            $this->pageDescription = preg_replace("/\s+/", " ", $this->pageDescription);
        }

        return $this->render('show', ['forum' => $forum]); //, 'comments' => $comments, 'videos' => $videos, 'pics' => $pics
    }
}
