<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../cebe/markdown/bin/markdown)
 * using a stream wrapper to prevent the shebang from being output on PHP<8
 *
 * @generated
 */

namespace app\controllers;

use Yii;
use FrontEndCotroller;
use app\models\Forum;
use app\models\Country;
use app\models\Region;
use app\models\City;
use app\models\ForumComment;
use app\models\ForumTag;
use yii\data\Pagination;

/**
 * Implements hook_help().
 */
class ForumController extends FrontEndController
{

    protected function __getQuery($countryId = 0, $regionId = 0, $cityId = 0, $tagId = 0)
    {
        $query =  Forum::find()->joinWith('user');
        $query->joinWith('country');
        $query->joinWith('region');
        $query->joinWith('city');
        if ($cityId != 0) $query->where(
            [
                'forum.city_id' => [$cityId, 0],
                'forum.region_id' => [$regionId, 0],
                'forum.country_id' => [$countryId],
                'forum.status' => [Forum::STATUS_APPROVED, Forum::STATUS_NEW]
            ]
        );

        if ($tagId > 0) {
            $query->joinWith('tags');
            $query->andWhere(['forum_to_forum_tag.forum_tag_id' => $tagId]);
        }


        //$query =  Forum::find()->joinWith('tags')->where(['forum_to_forum_tag.id' => 1]);


        return $query;
    }

    public function actionCity($link, $cityId = 0, $tagLink = null, $tagId = 0)
    {
        $city = City::find()->where(['id' => $cityId])->one();
        if ($city == null) {
            throw new \yii\web\NotFoundHttpException('Oopsss1');
        }

        $forumTag = null;
        if ($tagId > 0) {
            $forumTag = ForumTag::find()->where(['id' => $tagId]);
            if ($forumTag == null) throw new \yii\web\NotFoundHttpException('Oopsss2');
        }

        $region = $city->region;
        $country = $city->country;

        $query = $this->__getQuery(
            $city->country_id,
            $city->region_id,
            $city->id,
            $tagId
        );

        $countQuery = clone $query;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
            'pageSize' => 10,
            'pageSizeParam' => false,
            'validatePage' => false,
            'route' => 'forum/city'
        ]);

        $forums = $query->offset($pages->offset)
            ->orderBy('datetime_create DESC')
            ->limit($pages->limit)
            ->all();

        if ($pages->getPage() > $pages->getPageCount() || $pages->getPage() == 0 && Yii::$app->request->get('page') !== null) {
            return $this->redirect(['forum/city', 'link' => $city->link]);
        }

        $this->metaUrl = '[city_url]';
        $this->canonical = $city->getLink();

        $this->metaReplace = [
            '[city]' => $city->name,
            '[city_v]' => $city->name_v,
            '[city_net]' => $city->name_net,
            '[city_vin]' => $city->name_vin,
            '[city_url]' => $city->link,
            '[region]' => $region != null ? $region->name : '',
            '[region_v]' => $region != null ? $region->name_v : '',
            '[region_net]' => $region != null ? $region->name_net : '',
            '[region_url]' => $region != null ? $region->link : '',
            '[date]' => \app\lib\CommonLib::dateRu('F Y'),
            '[country]' => $country != null ? $country->name : '',
            '[country_v]' => $country != null ? $country->name_v : '',
            '[country_net]' => $country != null ? $country->name_net : '',
            '[country_vin]' => $country != null ? $country->name_vin : '',
            '[country_url]' => $country != null ? $country->link : '',
            '[v_vo_na]' => $country != null ? $country->v_vo_na : '',
            '[V_VO_NA]' =>  $country != null ? \app\lib\CommonLib::mb_ucfirst($country->v_vo_na) : ''
        ];

        return $this->render('city', ['forums' => $forums, 'pages' => $pages]);
    }

    public function actionShow($forum_id)
    {

        $forum = Forum::find()->where(['id' => $forum_id])->with('tags')->one();
        if ($forum === null)
            throw new \yii\web\NotFoundHttpException('Oopsss!');
        if (!$forum->isAvailable())
            throw new \yii\web\NotFoundHttpException('Oopsss!!');

        // if ($forum->city != null) $this->cityV = $forum->city;
        // else if ($forum->region != null) $this->regionV = $forum->region;
        // else if ($forum->country != null) $this->countryV = $forum->country;

        // $criteria = new CDbCriteria;
        // $criteria->condition = 'forum_id=:forum_id AND 
        //     (
        //         (status IN (' . ForumComment::STATUS_NEW . ',' . ForumComment::STATUS_APPROVED . ')) OR 
        //         (status=' . ForumComment::STATUS_DELETED . ' AND ip=INET_ATON(:ip) AND datetime_create>UNIX_TIMESTAMP()-3600) 
        //     )';
        // $criteria->params = array('forum_id' => $forum_id, 'ip' => $_SERVER['REMOTE_ADDR']);
        // $criteria->order = 'datetime_create ASC';
        // $comments = ForumComment::model()->with(array('user'))->findAll($criteria);

        $comments = ForumComment::find()
            ->where(
                'forum_id=:forum_id ',
                ['forum_id' => $forum->id]
            )
            ->orderBy('datetime_create ASC')
            ->all();
        //AND
        // (
        //     (status IN (' . ForumComment::STATUS_NEW . ',' . ForumComment::STATUS_APPROVED . ')) OR 
        //     (status=' . ForumComment::STATUS_DELETED . ' AND ip=:ip AND datetime_create > extract(epoch from now()) - 3600) 
        // )


        $tmp = array();
        foreach ($comments as $row) {
            $tmp[$row->id] = $row;
        }
        $comments = $tmp;
        unset($tmp);

        // $videos = ForumVideo::getVideoForum($forum_id);
        // $pics = ForumPhoto::getVideoForum($forum_id);
        $this->canonical = $forum->getLink();

        $this->h1 = $forum->title;
        if (!empty($forum->meta_title)) $this->pageTitle = $forum->meta_title;
        else $this->pageTitle = $forum->title;
        if (!empty($forum->meta_keyword)) $this->pageKeywords = $forum->meta_keyword;
        else $this->pageKeywords = $forum->title;
        if (!empty($forum->meta_description)) $this->pageDescription = $forum->meta_description;
        else {
            $this->pageDescription = trim(str_replace(array("\r", "\n"), ' ', $forum->getSubText()));
            $this->pageDescription = preg_replace("/\s+/", " ", $this->pageDescription);
        }

        return $this->render('show', ['forum' => $forum, 'comments' => $comments]); //, 'videos' => $videos, 'pics' => $pics
    }
}
