<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../cebe/markdown/bin/markdown)
 * using a stream wrapper to prevent the shebang from being output on PHP<8
 *
 * @generated
 */

namespace app\controllers;

use Yii;
use FrontEndCotroller;
use app\models\Organization;
use yii\data\Pagination;

/**
 * Implements hook_help().
 */
class OrganizationController extends FrontEndController
{

    public function actionIndex($inn)
    {

        $organizations = Organization::find()
            ->where('inn=:inn', ['inn' => $inn])
            ->all();

        return $this->render('index', ['organizations' => $organizations]);
    }
}
