<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../cebe/markdown/bin/markdown)
 * using a stream wrapper to prevent the shebang from being output on PHP<8
 *
 * @generated
 */

namespace app\controllers;

use Yii;
use FrontEndCotroller;
use app\models\Organization;
use yii\data\Pagination;
use yii\helpers\Url;

/**
 * Implements hook_help().
 */
class OrganizationController extends FrontEndController
{


    public function actionIndex()
    {
        $this->metaUrl = 'organizations';


        $query = Organization::find()->select('fullname, ogrn, type');
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 60, 'pageSizeParam' => false, 'validatePage' => false]);
        $organizations = $query->offset($pages->offset)
            ->orderBy('id DESC')
            ->limit($pages->limit)
            ->all();

        if ($pages->getPage() > $pages->getPageCount() || $pages->getPage() == 0 && Yii::$app->request->get('page') !== null) {
            return $this->redirect(['organization/list']);
        }

        $this->canonical = Url::toRoute('organization/index');
        return $this->render('index', ['organizations' => $organizations, 'pages' => $pages]);
    }

    public function actionInfo($inn)
    {

        $organizations = Organization::find()
            ->where('inn=:inn', ['inn' => $inn])
            ->all();
        if (count($organizations) == 0) {
            throw new \yii\web\NotFoundHttpException('Oopsss!');
        }
        $organization = $organizations[count($organizations) - 1];
        $this->metaUrl = 'inn[inn]';
        $this->metaReplace = ['[inn]' => $inn, '[name]' => $organization->fullname, '[ogrn]' => $organization->ogrn];
        $this->canonical = $organization->getUrl();
        return $this->render('info', ['organizations' => $organizations]);
    }

    public function actionOgrnip($ogrnip)
    {

        $organization = Organization::find()
            ->where('ogrn=:ogrn', ['ogrn' => $ogrnip])
            ->one();
        if ($organization == null) {
            throw new \yii\web\NotFoundHttpException('Oopsss!');
        }

        $this->metaUrl = 'ogrnip[number]';
        $this->metaReplace = ['[inn]' => $organization->inn, '[name]' => $organization->fullname, '[ogrn]' => $organization->ogrn];
        $this->canonical = $organization->getUrl();
        return $this->render('info2', ['organization' => $organization]);
    }
    public function actionOgrn($ogrn)
    {

        $organization = Organization::find()
            ->where('ogrn=:ogrn', ['ogrn' => $ogrn])
            ->one();
        if ($organization == null) {
            throw new \yii\web\NotFoundHttpException('Oopsss!');
        }

        $this->metaUrl = 'ogrn[number]';
        $this->metaReplace = ['[inn]' => $organization->inn, '[name]' => $organization->fullname, '[ogrn]' => $organization->ogrn];
        $this->canonical = $organization->getUrl();
        return $this->render('info2', ['organization' => $organization]);
    }
}
