<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../cebe/markdown/bin/markdown)
 * using a stream wrapper to prevent the shebang from being output on PHP<8
 *
 * @generated
 */

namespace app\controllers;

use Yii;
use FrontEndCotroller;
use app\models\CommentPhone;
use yii\data\Pagination;

/**
 * Implements hook_help().
 */
class PhoneController extends FrontEndController
{

    public function actionIndex()
    {
        $query = CommentPhone::find()->where(['status' => CommentPhone::STATUS_OK]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 60, 'pageSizeParam' => false, 'validatePage' => false]);
        $commentPhones = $query->offset($pages->offset)
            ->orderBy('datetime DESC')
            ->limit($pages->limit)
            ->all();

        if ($pages->getPage() > $pages->getPageCount() || $pages->getPage() == 0 && Yii::$app->request->get('page') !== null) {
            $this->redirect(['phone/']);
        }

        $this->metaUrl = 'phone';
        $this->canonical = '/phone';
        return $this->render('index', ['commentPhones' => $commentPhones, 'pages' => $pages]);
    }

    public function actionInfo($number)
    {

        $number = (string)$number;
        $numberFormat = $number;
        if (strlen($number) == 11) {
            $numberFormat = '+' . $number[0] . '(' . $number[1] . $number[2] . $number[3] . ')' . $number[4] . $number[5] . $number[6] . '-' . $number[7] . $number[8] . '-' . $number[9] . $number[10];
        } else {
            throw new \yii\web\NotFoundHttpException('Oopsss!');
        }

        $commentPhones = CommentPhone::find()
            ->where(
                'phone_number=:number',
                ['number' => substr($number, -10)]
            )
            ->orderBy('datetime DESC')
            ->all();

        $this->metaUrl = '[phone]';
        $this->metaFrom = ['[phone]'];
        $this->metaTo = [$numberFormat];
        $this->canonical = $commentPhones[0]->getUrl();
        return $this->render('info', ['number' => $number, 'numberFormat' => $numberFormat, 'commentPhones' => $commentPhones]);
    }
}
