<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../cebe/markdown/bin/markdown)
 * using a stream wrapper to prevent the shebang from being output on PHP<8
 *
 * @generated
 */

namespace app\controllers;

use Yii;
use FrontEndCotroller;
use app\models\CommentPhone;
use app\models\PhoneSearch;
use app\models\OrganizationPhone;
use app\lib\PhoneTool;
use app\models\PhoneInfo;
use Faker\Provider\bg_BG\PhoneNumber;
use yii\data\Pagination;

/**
 * Implements hook_help().
 */
class PhoneController extends FrontEndController
{

    public function actionIndex()
    {
        $query = CommentPhone::find()->where(['status' => CommentPhone::STATUS_OK]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 60, 'pageSizeParam' => false, 'validatePage' => false]);
        $commentPhones = $query->offset($pages->offset)
            ->orderBy('datetime DESC')
            ->limit($pages->limit)
            ->all();

        if ($pages->getPage() > $pages->getPageCount() || $pages->getPage() == 0 && Yii::$app->request->get('page') !== null) {
            return $this->redirect(['phone/']);
        }

        $this->metaUrl = 'phone';
        $this->canonical = '/phone';
        return $this->render('index', ['commentPhones' => $commentPhones, 'pages' => $pages]);
    }

    public function actionInfo($number)
    {
        if (isset($_GET['xxx'])) {
            $this->setSuccess('Спасибо, Ваше сообщение добавлено!');
            exit;
        }

        $number = (string)$number;
        $numberFormat = $number;
        if (strlen($number) == 11) {
            $numberFormat = '+' . $number[0] . '(' . $number[1] . $number[2] . $number[3] . ')' . $number[4] . $number[5] . $number[6] . '-' . $number[7] . $number[8] . '-' . $number[9] . $number[10];
        } else {
            throw new \yii\web\NotFoundHttpException('Oopsss!');
        }

        $model = new CommentPhone;

        if ($this->request->isPost) {
            $model->phone_number = $number;
            if ($model->load($this->request->post()) && $model->save()) {
                $this->setSuccess('Спасибо, Ваше сообщение добавлено!');
                return $this->redirect(['phone/info', 'number' => $number]);
            } else {
                $errors = $model->getErrors();
            }
        } else {
            $model->loadDefaultValues();
        }

        $commentPhones = CommentPhone::find()
            ->where(
                'phone_number=:number AND status=:status',
                ['number' => substr($number, -10), 'status' => CommentPhone::STATUS_OK]
            )
            ->orderBy('datetime DESC')
            ->all();


        $organizationPhone = OrganizationPhone::findOne(['number' => PhoneTool::phoneIn($number)]);
        $phoneInfo = PhoneInfo::findOne(PhoneTool::phoneIn($number));


        $this->metaUrl = '[phone]';
        $this->metaFrom = ['[phone]'];
        $this->metaTo = [$numberFormat];
        $this->canonical = Yii::$app->urlManager->createUrl(['phone/info', 'number' => $number]);
        return $this->render('info', [
            'phoneInfo' => $phoneInfo,
            'model' => $model,
            'number' => $number,
            'numberFormat' => $numberFormat,
            'commentPhones' => $commentPhones,
            'organizationPhone' => $organizationPhone,
        ]);
    }

    public function actionSearch($number)
    {
        $phoneSearch = new PhoneSearch;
        $phoneSearch->phone_number = $number;
        $phoneSearch->save();
        $this->setSuccess('У данного телефона повышенный приоритет');
        return $this->redirect(['phone/info', 'number' => $number]);
    }
}
