<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../cebe/markdown/bin/markdown)
 * using a stream wrapper to prevent the shebang from being output on PHP<8
 *
 * @generated
 */

namespace app\controllers;

use Yii;
use FrontEndCotroller;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Forum;


/**
 * Implements hook_help().
 */
class SiteController extends FrontEndController
{
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        // $connection = Yii::$app->db;
        //     $command = $connection->CreateCommand("SELECT * FROM pg_catalog.pg_tables WHERE schemaname != 'pg_catalog' AND  schemaname != 'information_schema';");
        //     $rows = $command->queryAll();
        //     print_r($rows);
        //     exit;
        //     $connection = Yii::$app->db;
        //     $command = $connection->CreateCommand("SELECT * FROM city;");
        //     $rows = $command->queryAll();
        //     foreach ($rows as $row){
        //         echo $row['name']."<br>";
        //     }
        //     exit;
        // $city = City::findOne(28);
        // print_r($city);
        // exit;
        // $meta = Meta::find('url LIKE \'index\'');
        // $this->view->title = '111';

        $this->metaUrl = 'index';
        $this->canonical = '/';


        // $criteria = new CDbCriteria;
        // $criteria->condition = 'tpl_id=0 AND type=:type';
        // $criteria->params = array('type' => Forum::TYPE_FORUM);
        // $criteria->addInCondition('status', Forum::$statusAvailable);
        // $criteria->order = 'datetime_create DESC';
        // $criteria->limit = 10;
        // $forums = Forum::model()->findAll($criteria);
        $forums = Forum::find()->where('tpl_id=0 AND status=:status', ['status' => Forum::STATUS_APPROVED])->orderBy('datetime_create DESC')->limit(10)->all();

        return $this->render('index', ['forums' => $forums]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}
