<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../cebe/markdown/bin/markdown)
 * using a stream wrapper to prevent the shebang from being output on PHP<8
 *
 * @generated
 */

namespace app\controllers_api;

use app\models\CommentPhone;
use yii\web\Controller;
use Yii;


/**
 * Implements hook_help().
 */
// class CommentPhoneController extends ApiController
class SiteController extends ApiController
{
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        // echo 6;
        // echo Yii::$app->urlManager->createUrl(['site/index']);
        return $this->render('index');
        //exit;
    }
    public function actionTest()
    {
        // echo 5;
        // echo Yii::$app->urlManager->createUrl(['site/test']);
        return $this->render('test');
        //print_r($this->viewPath);
        exit;
    }
    public function actionAdd($idext)
    {
        echo $idext;
        exit;
    }
}
